apiVersion: v1
kind: Deployment
metadata:
  name: time
  labels:
    name: time
spec:
  replicas: 2
  selector: 
   matchLabels:
     name: time
  template:
    metadata:
      name: time
    spec:
      containers:
       - image: tarangjain/time-date-go
         name: time
         ports:
         - containerPort: 8080
         