apiVersion: v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    name: test-deploy
spec:
  replicas: 2
  selector: 
   matchLabels:
     name: test
  template:
    metadata:
      name: time
    spec:
      containers:
       - image: tarangjain/time-date-go
         name: time
         ports:
         - containerPort: 8080
         