apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-1
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: current
        image: tarangjain/time-date-go
        ports:
         - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata: 
  name: currentdateandtime
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30008
  selector: 
    tier: frontend

---